#!/bin/bash
# displays disk usage statistics

# move to source directory
cd "$(dirname "$0")" || exit

source parameters
cd $recordings
du . -h | sort -hr | tail -n +2
df -h | head -1
df -h | grep home
cd -
