#!/bin/bash
######## global variables ########
bird_file="/home/kjbrown/panoptisong_acoustic/birds"
recordings="/home/kjbrown/acoustic_recordings"

experimenter="kjbrown"
room="010b"
species="zf"
lightson="09"
lightsoff="17"

# jack params
servername="acoustic"
jackdparams="-n $servername -d alsa -d hw:1 -r 32000 -p 2048"

# jdetect params
closeperiod="3000"
closethresh="0.02"
closerate="5"

# when to create a new file (24h time)
reset_time="00:00"
